name: build and publish

on:
  push:


jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: 'backstage/backstage'
        ref: 'v1.3.0'
        path: '.'

    - name: list dir
      uses: philips-labs/list-folders-action@v1
      with:
        path: .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: hartje
        password: ${{ secrets.DOCKERHUB_KEY }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          hartje/backstage:latest
          hartje/backstage:${{ github.sha }}
        platforms: linux/amd64

