name: build and publish

on:
  push:
    branches:
      - trunk
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: goshlanguage
        password: ${{ secrets.DOCKERHUB_KEY }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          hartje/backstage:latest
          hartje/backstage:${{ github.sha }}
        platforms: linux/amd64

